---

- hosts: all
  become: true
  tasks:

    - name: install updates (Amazon)
      tags: always
      yum:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "Amazon"

    - name: install updates (Ubuntu)
      tags: always
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"


- hosts: web_severs
  become: true
  tasks:


  - name: install apache2 package, php and update cache for ubuntu
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 package, php and update cache for ubuntu
    tags: apache, Amazon, httpd,php
    yum:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Amazon"

- hosts: db_servers
  become: true
  tasks:

    - name: install mariadb package (Amazon Linux)
      tags: Amazon,db,mariadb
      yum:
        name: mariadb
        sate: latest
      when: ansible_distribution == "Amazon"

    - name: install mariadb package (Ubuntu)
      tags: ubuntu,db,mariadb
      apt:
       name: mariadb-server
       state: latest
      when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:
     
    - name: install samba package
      tags: samba
      package:
        name: samba
        state: latest
