- name: install apache and php packages
  tags: apache,apache2,Amazon,httpd,ubuntu
  package:
     name:
       - "{{ apache_package_name }}"
       - "{{ php_package_name }}"
     state: latest
  when: ansible_distribution == "Amazon"
  
 
- name: start and enable apache service
  tags: apache,Amazon,httpd
  service:
     name: "{{ apache_service }}"
     state: started
     enabled: yes
  when: ansible_distribution == "Amazon"
 
- name: change e-mail address for admin
  tags: apache,Amazon,httpd
  lineinfile:
     path: /etc/httpd/conf/httpd.conf
     regexp: '^ServerAdmin'
     line: ServerAdmin felix-ayo@gmail.org
  when: ansible_distribution == "Amazon"
  notify: restart_apache 


- name: restart httpd
  tags: apache,httpd
  service:
    name: "{{ apache_service }}"
    state: restarted
  when: ansible_distribution == "Amazon"
   
 
- name: copy html file for site
  tags: apache,apache,apache2,httpd
  copy:
     src: default_site.html
     dest: /var/www/html/index.html
     owner: root
     group: root
     mode: 0644



