- name: install apache2 package, php and update cache for ubuntu
  tags: apache,apache2,ubuntu
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: install apache2 package, php and update cache for ubuntu
  tags: apache, Amazon, httpd,php
  yum:
     name:
      - httpd
      - php
     state: latest
  when: ansible_distribution == "Amazon"


- name: start and enable httpd (Amazon)
  tags: apache,Amazon,httpd
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "Amazon"
